### ISSUE TITLE
Unable to save Gyazo access token

### ISSUE THREAD

**Issue by ashishbhateja** [qawatake/obsidian-toolbox-plugin#9]
Hi,

I installed this plugin via BRAT. I try to enter my gyazo access token in the settings but it keeps showing a blank box. Can you help tropubleshoot?

**Comment by qawatake** [comment]
@ashishbhateja 

The token form will be cleared on submission.

Please check the content of `.obsidian/plugins/obsidian-toolbox-plugin/data.json`.
Your access token will be stored in `minimalPlugins: gyazo: data: accessToken`.

**Comment by ashishbhateja** [comment]
Thanks, got it.

**Comment by ashishbhateja** [comment]
Thank you, got it!

On May 29, 2022 at 4:21 GMT, qawatake ***@***.***> wrote:

***@***.***(https://github.com/ashishbhateja)

The token form will be cleared on submission.

Please check the content of .obsidian/plugins/obsidian-toolbox-plugin/data.json.
Your access token will be stored in minimalPlugins: gyazo: data: accessToken.
